//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day4WebService_Client.ZensarServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZensarServices.MyWebservices1Soap")]
    public interface MyWebservices1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Day4WebService_Client.ZensarServices.HelloWorldResponse HelloWorld(Day4WebService_Client.ZensarServices.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Day4WebService_Client.ZensarServices.HelloWorldResponse> HelloWorldAsync(Day4WebService_Client.ZensarServices.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name str from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        Day4WebService_Client.ZensarServices.MessageResponse Message(Day4WebService_Client.ZensarServices.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Message", ReplyAction="*")]
        System.Threading.Tasks.Task<Day4WebService_Client.ZensarServices.MessageResponse> MessageAsync(Day4WebService_Client.ZensarServices.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindSqaure", ReplyAction="*")]
        float FindSqaure(float num);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindSqaure", ReplyAction="*")]
        System.Threading.Tasks.Task<float> FindSqaureAsync(float num);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Day4WebService_Client.ZensarServices.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Day4WebService_Client.ZensarServices.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Day4WebService_Client.ZensarServices.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Day4WebService_Client.ZensarServices.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Message", Namespace="http://tempuri.org/", Order=0)]
        public Day4WebService_Client.ZensarServices.MessageRequestBody Body;
        
        public MessageRequest() {
        }
        
        public MessageRequest(Day4WebService_Client.ZensarServices.MessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string str;
        
        public MessageRequestBody() {
        }
        
        public MessageRequestBody(string str) {
            this.str = str;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Day4WebService_Client.ZensarServices.MessageResponseBody Body;
        
        public MessageResponse() {
        }
        
        public MessageResponse(Day4WebService_Client.ZensarServices.MessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MessageResult;
        
        public MessageResponseBody() {
        }
        
        public MessageResponseBody(string MessageResult) {
            this.MessageResult = MessageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyWebservices1SoapChannel : Day4WebService_Client.ZensarServices.MyWebservices1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyWebservices1SoapClient : System.ServiceModel.ClientBase<Day4WebService_Client.ZensarServices.MyWebservices1Soap>, Day4WebService_Client.ZensarServices.MyWebservices1Soap {
        
        public MyWebservices1SoapClient() {
        }
        
        public MyWebservices1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyWebservices1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebservices1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyWebservices1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Day4WebService_Client.ZensarServices.HelloWorldResponse Day4WebService_Client.ZensarServices.MyWebservices1Soap.HelloWorld(Day4WebService_Client.ZensarServices.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Day4WebService_Client.ZensarServices.HelloWorldRequest inValue = new Day4WebService_Client.ZensarServices.HelloWorldRequest();
            inValue.Body = new Day4WebService_Client.ZensarServices.HelloWorldRequestBody();
            Day4WebService_Client.ZensarServices.HelloWorldResponse retVal = ((Day4WebService_Client.ZensarServices.MyWebservices1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Day4WebService_Client.ZensarServices.HelloWorldResponse> Day4WebService_Client.ZensarServices.MyWebservices1Soap.HelloWorldAsync(Day4WebService_Client.ZensarServices.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Day4WebService_Client.ZensarServices.HelloWorldResponse> HelloWorldAsync() {
            Day4WebService_Client.ZensarServices.HelloWorldRequest inValue = new Day4WebService_Client.ZensarServices.HelloWorldRequest();
            inValue.Body = new Day4WebService_Client.ZensarServices.HelloWorldRequestBody();
            return ((Day4WebService_Client.ZensarServices.MyWebservices1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Day4WebService_Client.ZensarServices.MessageResponse Day4WebService_Client.ZensarServices.MyWebservices1Soap.Message(Day4WebService_Client.ZensarServices.MessageRequest request) {
            return base.Channel.Message(request);
        }
        
        public string Message(string str) {
            Day4WebService_Client.ZensarServices.MessageRequest inValue = new Day4WebService_Client.ZensarServices.MessageRequest();
            inValue.Body = new Day4WebService_Client.ZensarServices.MessageRequestBody();
            inValue.Body.str = str;
            Day4WebService_Client.ZensarServices.MessageResponse retVal = ((Day4WebService_Client.ZensarServices.MyWebservices1Soap)(this)).Message(inValue);
            return retVal.Body.MessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Day4WebService_Client.ZensarServices.MessageResponse> Day4WebService_Client.ZensarServices.MyWebservices1Soap.MessageAsync(Day4WebService_Client.ZensarServices.MessageRequest request) {
            return base.Channel.MessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Day4WebService_Client.ZensarServices.MessageResponse> MessageAsync(string str) {
            Day4WebService_Client.ZensarServices.MessageRequest inValue = new Day4WebService_Client.ZensarServices.MessageRequest();
            inValue.Body = new Day4WebService_Client.ZensarServices.MessageRequestBody();
            inValue.Body.str = str;
            return ((Day4WebService_Client.ZensarServices.MyWebservices1Soap)(this)).MessageAsync(inValue);
        }
        
        public float FindSqaure(float num) {
            return base.Channel.FindSqaure(num);
        }
        
        public System.Threading.Tasks.Task<float> FindSqaureAsync(float num) {
            return base.Channel.FindSqaureAsync(num);
        }
    }
}
