// <auto-generated />
namespace CodeFirstPrj.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Addedbalancecolumninaccounts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedbalancecolumninaccounts));
        
        string IMigrationMetadata.Id
        {
            get { return "202205240816466_Added balance column in accounts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
